# projeto_atech
# compose syntax version.
version: "3.6"

# services declaration.
services:
  # PostgreSQL
  postgres:
    image: kartoza/postgis
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=projeto_atech
    ports:
      - target: 5432
        published: 5432
    networks:
      - postgres-compose-network
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "allan@uol.com.br"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - postgres-compose-network

# volumes declaration.
volumes:
  # postgres-data
  postgres-data:
    driver: local

networks: 
  postgres-compose-network:
    driver: bridge