# projeto_atech
# compose syntax version.
version: "3.6"

# services declaration.
services:
  # PostgreSQL
  postgres:
    image: kartoza/postgis
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=projeto_atech
    ports:
      - target: 5432
        published: 5432

# volumes declaration.
volumes:
  # postgres-data
  postgres-data:
    driver: local